### PR TITLE
Add RTL support

### PR DESCRIPTION
**Pull request by PejmanNik**
Add RTL(right to left) language support
to applay it just add `dir="rtl"` to the `html` element: `<html dir="rtl">`

### CODE REVIEW

**Comment by shentao** [comment]
Could you elaborate? Also please add this change to the `scr/Multiselect.vue` file rather than to the dist file.

**Comment by PejmanNik** [comment]
Sorry for that
I fix it and add change to `scr/Multiselect.vue`
for more elaborate:
to make `vue-multiselect` support RTL language we need make text right to left so by adding `dir="rtl"` to the `html ` tag of main `html` file `vue-multiselect` support RTL. 

like this:

multi
single

**Comment by shentao** [comment]
Thanks for the contribution!

**Comment by eybarta** [comment]
sweet thx! almost did this myself, but glad I found you did first..
* one css thing I needed to add:
`[dir=rtl] .multiselect__tags { text-align: right; }`

**Comment by shentao** [comment]
Would you like to provide a PR with that change? @eybarta

**Pull request merged**
