### PR TITLE
Added disabled functionality

### PR DESCRIPTION
**Pull request by adrianthedev**
Added the `disabled` prop and the apropiate class and attribute bindings.

### CODE REVIEW

**Comment by shentao** [comment]
Looks nice! I will try it out in the coming days, add some tests and incorporate it in the 1.0 release, which is mostly done (still working on the proper docs rework). Preview can be seen here: #57 

Thanks a lot @adrianthedev!

**Comment by adrianthedev** [comment]
I'm not very well versed in JS testing but I'll give it a try this evening. :smile: 

Cheers,

**Comment by shentao** [comment]
That would be great! :)

**Comment by shentao** [comment]
Added in v1.0.0. Thanks! :)

**Pull request closed without merging**
