### PR TITLE
Selected null passed from parent raises exception: Chapter 2.

### PR DESCRIPTION
**Pull request by asvae**
Still broken :).

### CODE REVIEW

**Comment by shentao** [comment]
Hm, I would try looking into the line that changes the search value to the selected value.

**Comment by asvae** [comment]
@shentao probably `getOptionLabel` could return `''` on null instead of `option`.

**Comment by shentao** [comment]
This is what I'm talking about :D I'm leaving for vacation for a week so I will merge everything next month. ;)

**Comment by asvae** [comment]
@shentao sure. Have fun.
BTW Got nasty preload on inactive select (many many `on-search-change` events for large forms). Will try to build a PR in that week.

**Comment by shentao** [comment]
Awesome! I really appreciate your commitment! Great job!

**Comment by asvae** [comment]
> probably getOptionLabel could return '' on null instead of option.

That was a bad idea. Everything breaks :\.

**Comment by shentao** [comment]
Could you test this on v1.0.1?

**Comment by asvae** [comment]
@shentao sure, will do tomorrrow.

**Comment by shentao** [comment]
Thanks!

**Comment by asvae** [comment]
@shentao wow. Everything works. Even removed all my duct-tape.

Good job!

**Comment by shentao** [comment]
Glad to hear that! :D

**Pull request closed without merging**
