### PR TITLE
Close when clicked on selected option when allowEmpty false

### PR DESCRIPTION
**Pull request by azamat-sharapov**
ref #230 

Will this do or do we need extra prop to switch this behavior?

### CODE REVIEW

**Comment by SirLamer** [comment]
I kinda like that it doesn't close when the selected value is clicked because it tells the user that their action had no effect. They can also click away.

**Comment by azamat-sharapov** [comment]
@SirLamer I also thought so, but I think following native `<select>` element behavior is better. When you click on selected element, `<select>` closes.

**Comment by SirLamer** [comment]
Yes you are right, good argument.

**Comment by alexxlagutin** [comment]
Hey! I also need native <select> behavior with allowEmpty: false for my project. Will this Azamat`s update be implemented?

**Comment by shentao** [comment]
Will be looking into it during the holidays. Thanks for contributing. Sorry for the delay.

**Comment by blackfyre** [comment]
Can we get an ETA on this?
I know it's an open source project but this PR has been sitting here for 5+ months now...

**Comment by shentao** [comment]
Won’t merge because there’s no need to modify the `dist`/`lib` files. Copied the needed code.
Will be released today. Thanks! :)

**Pull request closed without merging**
