### PR TITLE
Progress on vue2.0.0

### PR DESCRIPTION
**Pull request by CinKon**
Replaced `$els` with `$refs`
Replaced `this.$set`with `Vue.set`
Replaced `track-by` with `:key`
Worked on `filter`-functions
Fixed Prop-Type errors

### CODE REVIEW

**Comment by CinKon** [comment]
This is far from finished, but a basic-working starting point :)

**Comment by shentao** [comment]
Hey there! 

This is basically what I wanted to do with the 1.0 release – prepare it for an easy migration to support Vue 2.0. The 2.0 release of vue-multiselect was planned to shortly follow the official release of Vue 2.0.

Obviously, this can not be merged right now. I hope to finish the 1.0 release by the end of the week (including new docs). After this, I will create a new 2.0 dev branch where we can safely merge this and further work on supporting Vue 2.0. Wdyt?

Also big thanks for commitment! 👻

**Comment by CinKon** [comment]
I used your 1.0 pre-release as base ;)
I know you wanted to wait with the work on 2.0 till the release, but since i need it just now, i started with it. 
You can decide yourself, wether you use my request or not. ;)
This component is awesome, and i hope i can help to contribute.

**Comment by shentao** [comment]
Not with the work, just with the release. 
Sure thing!
The changes look good so I will most probably use them! :)

**Pull request closed without merging**
