### PR TITLE
Fix clear error

### PR DESCRIPTION
**Pull request by SirLamer**
Due a 2.0 branch change, if the field is cleared then it generates an error. This is a hacky fix to correct that. My objective here was to minimize changes to the code in order to affect a repair, but... really, the code needs some refactoring. I'd be willing to help with that but not before all of these open pull requests are resolved.

I didn't recompile just to dodge expected collisions from the PRs.

### CODE REVIEW

**Comment by shentao** [comment]
Thanks for the contribution!
Could you please run the tests and see if all of them pass? If not, correct them?

**Comment by SirLamer** [comment]
This passes the tests.

**Comment by shentao** [comment]
@SirLamer This will fail for `value == 0` as it will be considered as false. Also though it passes the tests, we don’t have tests for this specific behavior.
I might fix this after work, so around 8 PM CET. Could you rebase your branch till then?

**Comment by SirLamer** [comment]
ok that other PR from @pczarn addresses your request.

**Pull request closed without merging**
