### PR TITLE
add mousedown event to multiselect-single

### PR DESCRIPTION
**Pull request by mmsch**
Hi, Just added a small quickfix for IE. Maybe you can use it. #380

### CODE REVIEW

**Comment by shentao** [comment]
Looks good, thanks a lot @mmsch! Will try it out today and merge it afterwards.

**Comment by lafsar** [comment]
Any way we can expedite this merge? My users are having this issue as well.

**Comment by mmsch** [comment]
Hi @shentao! Added another commit for #363.

**Comment by shentao** [comment]
Thanks a lot! Sorry for the very very very late merge... Got overwhelmed by all the issues and now I’m trying to get back to active maintenance. :/

**Pull request merged**
