### PR TITLE
add dataTag to distinguish multiple vue-multiselect components

### PR DESCRIPTION
**Pull request by JeOam**
while trying to use vue-multiselect in a `for in` loop, there is no way i can distinguish which `$index` emited the on-change callback.

### CODE REVIEW

**Comment by shentao** [comment]
Hey! I’m currently working on the 1.0 release, which you can see here #57. You can try it yourself by using `npm install vue-multiselect@next`.
1.0 implements an `id` prop that is then passed as the second argument to each event. In this case it would be `@update` which replaces `:on-change` prop.

https://github.com/monterail/vue-multiselect/pull/57/files#diff-6b5af0f1e9c993645e63370d4087a280R185

https://github.com/monterail/vue-multiselect/pull/57/files#diff-6b5af0f1e9c993645e63370d4087a280R323

**Comment by JeOam** [comment]
@shentao 👍, ok, I close this PR right now.  May I ask if this is a release date for the 1.0 release?

**Comment by shentao** [comment]
It is mostly done, still have to add small tweaks and two additional events. And then finish the new documentation and upgrade guide. I hope to do this by the end of the week. The current beta is quite stable so you can already use it. The docs are also partially updated so just run it locally to see how to work with it.

**Comment by JeOam** [comment]
@shentao cool, I will use the beta version in our project, thank you!

**Pull request closed without merging**
